### ISSUE TITLE
not work when npm run dev

### ISSUE THREAD

**Issue by Delari** [omidkrad/vue-paper-dashboard-typescript#1]
Warning: The 'no-unused-variable' rule requires type information.
Warning: The 'no-use-before-declare' rule requires type information.
ts-loader: Using typescript@2.9.2 and C:\Users\Delari\Downloads\vue-paper-dashboard-typescript-master\vue-paper-dashboard-typescript-master\tsconfig.json
No valid rules have been specified for JavaScript files

 ERROR  Failed to compile with 8 errors                                                          12:44:14

 error  in C:\Users\Delari\Downloads\vue-paper-dashboard-typescript-master\vue-paper-dashboard-typescript-master\node_modules\vue-router\types\router.d.ts

(4,35): error TS2709: Cannot use namespace 'Vue' as a type.

 error  in C:\Users\Delari\Downloads\vue-paper-dashboard-typescript-master\vue-paper-dashboard-typescript-master\node_modules\vue-router\types\router.d.ts

(13,43): error TS2709: Cannot use namespace 'Vue' as a type.

 error  in C:\Users\Delari\Downloads\vue-paper-dashboard-typescript-master\vue-paper-dashboard-typescript-master\node_modules\vue-router\types\router.d.ts

(19,8): error TS2709: Cannot use namespace 'Vue' as a type.

 error  in C:\Users\Delari\Downloads\vue-paper-dashboard-typescript-master\vue-paper-dashboard-typescript-master\node_modules\vue-router\types\router.d.ts

(93,25): error TS2709: Cannot use namespace 'Vue' as a type.

 error  in C:\Users\Delari\Downloads\vue-paper-dashboard-typescript-master\vue-paper-dashboard-typescript-master\node_modules\vue-router\types\vue.d.ts

(17,13): error TS2428: All declarations of 'ComponentOptions' must have identical type parameters.

 error  in C:\Users\Delari\Downloads\vue-paper-dashboard-typescript-master\vue-paper-dashboard-typescript-master\node_modules\vue-router\types\vue.d.ts

(17,40): error TS2709: Cannot use namespace 'Vue' as a type.

 error  in C:\Users\Delari\Downloads\vue-paper-dashboard-typescript-master\vue-paper-dashboard-typescript-master\node_modules\vue\types\options.d.ts

(67,18): error TS2428: All declarations of 'ComponentOptions' must have identical type parameters.

 error  in ./src/main.ts

(28,30): error TS2345: Argument of type '{ routes: ({ [x: string]: any; path: string; component: VueConstructor<Vue>; redirect: string; ch...' is not assignable to parameter of type 'RouterOptions | undefined'.
  Type '{ routes: ({ [x: string]: any; path: string; component: VueConstructor<Vue>; redirect: string; ch...' is not assignable to type 'RouterOptions'.
    Types of property 'routes' are incompatible.
      Type '({ [x: string]: any; path: string; component: VueConstructor<Vue>; redirect: string; children?: u...' is not assignable to type 'RouteConfig[] | undefined'.
        Type '({ [x: string]: any; path: string; component: VueConstructor<Vue>; redirect: string; children?: u...' is not assignable to type 'RouteConfig[]'.
          Type '{ [x: string]: any; path: string; component: VueConstructor<Vue>; redirect: string; children?: un...' is not assignable to type 'RouteConfig'.
            Type '{ [x: string]: any; path: string; component: VueConstructor<Vue>; redirect: string; children?: un...' is not assignable to type 'RouteConfig'.
              Types of property 'component' are incompatible.
                Type 'VueConstructor<Vue>' is not assignable to type 'ComponentOptions<any, DefaultData<any>, DefaultMethods<any>, DefaultComputed, PropsDefinition<Rec...'.
                  Type 'VueConstructor<Vue>' is not assignable to type 'AsyncComponentFactory<DefaultData<never>, DefaultMethods<never>, DefaultComputed, Record<string, ...'.
                    Type 'VueConstructor<Vue>' provides no match for the signature '(): { component: AsyncComponentPromise<DefaultData<never>, DefaultMethods<never>, DefaultComputed, Record<string, any>>; loading?: VueConstructor<Vue> | FunctionalComponentOptions<Record<string, any>, PropsDefinition<Record<string, any>>> | ComponentOptions<never, DefaultData<never>, DefaultMethods<never>, DefaultComputed, Record<string, any>, Record<string, any>> | EsModuleComponent | undefined; error?: VueConstructor<Vue> | FunctionalComponentOptions<Record<string, any>, PropsDefinition<Record<string, any>>> | ComponentOptions<never, DefaultData<never>, DefaultMethods<never>, DefaultComputed, Record<string, any>, Record<string, any>> | EsModuleComponent | undefined; delay?: number | undefined; timeout?: number | undefined; }'.

> Listening at http://localhost:8080

**Comment by omidkrad** [comment]
Sorry, I don't maintain this project. We moved to using [Vue Paper Dashboard 2 Pro](https://www.creative-tim.com/product/vue-paper-dashboard-2-pro) which uses CLI 3 that supports TypeScript.

**Comment by Delari** [comment]
Tell me, then, how can I download it if I acquired licensing for your project?


чт, 20 дек. 2018 г. в 14:58, Omid K. Rad <notifications@github.com>:

**Comment by omidkrad** [comment]
It's not my product, we bought it from creative-tim. You may want to ask them to upgrade their free version of [vue-paper-dashboard](https://github.com/creativetimofficial/vue-paper-dashboard) to support CLI3. They are very responsive.
